# Generated by Django 3.2 on 2021-05-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hyfed_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlimmaProjectModel',
            fields=[
                ('hyfedprojectmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hyfed_server.hyfedprojectmodel')),
                ('normalization', models.CharField(default='UQ', max_length=512)),
                ('min_count', models.PositiveIntegerField(default=10)),
                ('min_total_count', models.PositiveIntegerField(default=15)),
                ('group1', models.CharField(default='', max_length=512)),
                ('group2', models.CharField(default='', max_length=512)),
                ('confounders', models.CharField(default='', max_length=512)),
            ],
            bases=('hyfed_server.hyfedprojectmodel',),
        ),
    ]
